### ISSUE TITLE
horarios de llegada a siguientes estaciones

### ISSUE THREAD

**Issue by rusosnith** [goncy/trenes#2]
Seria genialisimo que al seleccionar un tren (de los que estan visibles) se despliegue algun slider que muestre los horarios a los que llega a las siguientes estaciones.

**Comment by goncy** [comment]
Esta data no me viene en los servicios que obtengo, tendria que pegarle a otro servicio y no se si vale la pena, lo pateo para analizarlo despues!

**Comment by rusosnith** [comment]
Si, nada de esto es "urgente' solo lo dejaba por aqui
no los cierres que quizas algun otro los hace!
