### ISSUE TITLE
tooltips se superponen (mobile)

### ISSUE THREAD

**Issue by rusosnith** [goncy/trenes#3]
si seleccionas una estación, y se despliega el tooltip, luego clickeas el tren y al abrirse el tooltip se superponen. (se debería cerrar el anterior, permitiendo solo 1 tooltip a la vez)
*en movil*

**Comment by goncy** [comment]
Tuve en mente eso en un momento, lo que pasa es que cada tren, es un elemento diferente, ni se conocen con los otros trenes, por lo que tienen sus eventos aislados y separados, podria analizarlo pero lo veo mas dificil!

**Comment by goncy** [comment]
Lo pateo para despues!
